schema_version: 1

context:
  name: stringthings
  version: "0.2.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/stringthings-${{ version }}.tar.gz
  sha256: db2521ff404d31e981e1f658b892c1441541ed263105ccdccf5d35fce31bc00c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - pandas

tests:
  - python:
      imports:
        - stringthings
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: some functions to work with strings.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ayaranitram/stringthings

extra:
  recipe-maintainers:
    - jan-janssen
